dubbo:
  application:
    name: boot-user-service-provider
    qosEnable: false
    qosPort: 33333
    qosAcceptForeignIp: false
  registry:
    address: zookeeper://182.254.183.22:2181
  protocol:
    name: dubbo
#    dubbo的配置信息加载顺序是 -D > application.yml > dubbo.properties
    port: 20880
#  monitor:
#    protocol: registry
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true #开启本地存储
  redis:
    databases: 0 #reids 数据库索引
    host: 182.254.183.22
    port: 6379
    password:  # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    time: 1000 # 连接超时时间（毫秒）


apache:
  rocketmq:
    # 消费者的组名
    consumer:
      pushConsumer: PushConsumer
    # 生产者的组名
    producer:
      producerGroup: Producer
    # NameServer地址
    namesrvAddr: 182.254.183.22:9876