dubbo:
  application:
    name: boot-user-service-provider
  registry:
    address: zookeeper://182.254.183.22:2181
  protocol:
    name: dubbo
#    dubbo的配置信息加载顺序是 -D > application.yml > dubbo.properties
    port: 20881
  monitor:
    protocol: registry
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
apache:
  rocketmq:
    # 消费者的组名
    consumer:
      pushConsumer: PushConsumer
    # 生产者的组名
    producer:
      producerGroup: Producer
    # NameServer地址
    namesrvAddr: 182.254.183.22:9876