dubbo:
  application:
    name: boot-user-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
#    dubbo的配置信息加载顺序是 -D > application.yml > dubbo.properties
    port: 20881
  monitor:
    protocol: registry
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 182.254.183.22:9300
      repositories:
        enabled: true
